version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    depends_on:
      - selenium-chrome
    restart: unless-stopped
    networks:
      - scraper-network

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    platform: linux/amd64
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "3g"
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=60
    restart: unless-stopped
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge